# Generated by Django 4.2.5 on 2023-11-10 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partytime_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contacts',
            new_name='contact',
        ),
    ]
