# Generated by Django 4.2.7 on 2023-11-11 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partytime_app', '0002_rename_contacts_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact',
        ),
    ]
