# Generated by Django 4.2.7 on 2023-11-11 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partytime_app', '0003_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=1000000)),
                ('uploaded_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
