# Generated by Django 4.2.7 on 2023-11-11 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partytime_app', '0004_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blogs',
            new_name='blog',
        ),
    ]
