# Generated by Django 4.2.7 on 2023-11-12 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partytime_app', '0011_alter_service_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
