# Generated by Django 4.2.7 on 2023-11-15 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partytime_app', '0014_alter_service_image'),
    ]

    operations = [
    ]
